import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>The Wub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Saurabh Bhatia
        </h1>

        <p className={styles.description}>
          Software Developer, Author, Writer, Speaker, Artist
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <Link href="/resume">
              <a><h2>&#9681; Resume</h2></a>
            </Link>
          </div>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>&#9683; Writing</h2>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>&#9682; Talks</h2>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>&#9680; Github</h2>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>&#9677; Articles</h2>
          </a>
        </div>
      </main>
    </div>
  )
}
